apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter
  name: greeter
spec:
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    protocol: TCP
  selector:
    app: greeter
  sessionAffinity: None
  type: ClusterIP
